version: "3.8"

services:

    client:
        build:
            context: .
            dockerfile: etc/docker/Dockerfile.client.debug
            target: production
        ports:
            - 3001
        restart: always

    api:
        build:
            context: .
            dockerfile: etc/docker/Dockerfile.api.debug
            target: production
        ports:
            - 3002
        restart: always

    nginx:
        depends_on:
            - api
            - client
        build:
            context: .
            dockerfile: etc/docker/nginx-debug.Dockerfile
        ports:
            - 80:80
            - 443:443
        restart: always